### ISSUE TITLE
Transfer this repository to @jimmywarting

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/jimmywarting-.github#1]
Hi @jimmywarting! 👋

I've noticed that you have a bunch of FUNDING.yml files in your repositories that could be consolidated into a single jimmmywarting/.github repository. I have requested to transfer ownership of this repository that I think is a good baseline so you don't need to add `.github/FUNDING.yml` to each new repo that you create 😉

**If you prefer not to have this, that's OK too! ❤️**

In the future, such a .github repository could also help with any of:

1. Adding GitHub Actions workflow templates that show up in the "Create a workflow" wizard https://dev.to/jcbhmr/til-you-can-create-your-own-github-actions-workflow-templates-41e4
2. Adding a generic CONTRIBUTING.md guide with your preferences like "use JSDoc" or whatever
3. Adding a user-specific wiki that you can point to like https://github.com/jcbhmr/.github/wiki instead of re-writing the same comment when someone asks you "why do you do it this way?" 👈 this is actually something that I've only recently started doing.
4. Add more default community files like SECURITY.md which might say "report it to the GitHub Security tab" or something. Or maybe a SUPPORT.md. Check https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file
6. ~~(If you don't care much for security segmentation and the risk is low) syncing a single user-wide `NPM_TOKEN` secret from .github to specific low-impact npm package repositories~~

🛑 Remember to rename this repo to `.github` 😁

**Comment by jimmywarting** [comment]
Thanks, going to try this out.

**Comment by jimmywarting** [comment]
You seem to know so much about github 🧠  
And all your emoji put such a nice touch to everything 😉

**Comment by jimmywarting** [comment]
I have this private github repo/template that i'm always using when creating new repos.

**Comment by jcbhmr** [comment]
Look at this! It works! 🥳  https://github.com/jimmywarting/wemo-client
![image](https://github.com/jimmywarting/.github/assets/61068799/f2d5fc91-e464-4c2f-a318-707713e5b347)
👆 No .github/FUNDING.yml that I could see
👇 and you still get the sponsors sidebar!
![image](https://github.com/jimmywarting/.github/assets/61068799/ce2f74ec-c650-4756-89f3-97a5e2f85702)

**Comment by jimmywarting** [comment]
Yay!
